apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my-secret
  namespace: forager-helm
spec:
  encryptedData:
    mysql_password: AgBijIbXrHX3o7kiaxsEHD9cooQRVhrFe7qxr8VQyFVHrOimpn6QPstzkIMlulbE57W54C/OXNMbFxLHuqYVXPHtXbD5uon++ENvv8ERWs/yoQyKsZHabhThugOYdqJxkyNe2zKjYM7ZitIUTMqNFQfrf4dLiPc+GvCvewIrenw1xKYnVleSsvlM60RnJl/vAayLEZ7+hj05gjO9myv199HqX7Qh91/8QBhQFUyUXbsSj70qpd5YOUFEBVDLlSNj/opjECpiWObK8UC4dxwQ30EltrzAQTMyYSWqsrH+SYWwpqm5VrGI07CTQgO+2BlhOimMAyb0CeN/RAKksnaFEoy0XFyN5gjJ6g0r2AW4rh1tz9L2iaKaS797vc2B3jBCKcGqzVNApFwbV9CYPcKS4zrl7ZQN3c9YlOEHS3fQAjgPd6GAb9uAbn0I758r43/qjTxQg75ZIlrtfgGKROdQjm3TGf5hx5UjzkzKiAHp6O15zGVffR0j7rlaxkGEVzmHTsLaTVpXc/ds8PNg0kflzFp+MfIE3PboIrZOlwX3xhaFxrclOiCGUVd9jTlx7suGEyf6AQ/wsUdikjsMoHgK3aQXvMXBTRr1yYyxuZXsIrKLJx2acIO+4EdNebJVoVPBI/S1CcipqnvntwCo18uknDGtRRI/5xkrrbJKtY1eCE8JwsdQLSRW4DjLR1AMw/RaelwaihBcKd34Ug==
    password: AgAy/lCM6Q6QHY1jGpyTDfqbVFlWwQFiQXtEkm/trtV0DTcLVpskf/Tu8TuIef3mPyT9T7Wu+wBRZ3Knp7S2zpmUaCm7kgcla8yAGUtBTQFKXC7KdvHWIlks+Mf6IJ5Ekek64e2o7iO4+netWpIqhVvCjL/gKftyftC/rs1kO8kd9f0SiQYl/75VxxOQCA8WZM9Vs8N3cjvy7rLII3jeP8kJvUzhTLgOx0mL1+bat5TlrZh9JXEDsLLO1XUTW8hpmHNo9PLIFUiIKdC0P+CVnu0WiscPFOBMDs9QAa32ZDvZigLzqR6epO73hWU1mmDcrfGun5PrcgsgmnmNL7syjArBqO17qOtLzhw+uewvFBJPEp3q/Q74k5e73pIJcIGrsT/n9W9G0gt1xS9dg+JdslkrYnhCXRp4TrL7mWAuBepkfxhk4EA/AVIgkLCnpHDp04C5tIsd8X+GuzJuZCPD6DS9795/jkgCpT7UA8Z1nt/iIpe8fn+bLKxeUWwBEKxJ5yl85sIdQAEJcGk5vauTugJtSr07qcsLiSrhVEWB5B40ThCeJGYxLiOsTTKK3OrFdk7S5UtrJGZpio3CzrCJFgrsgCZ//tD6mHpqPnwRsIPiDD38bLPlulpW7MDDkzo/qA+EhtdpryMjfScOaGHha1nk99ehHJIUV+iZsTy3Vh+YQD6D/60lGKSBDDDAjkUtDbEKp72DCBzc7Q==
    username: AgA3sn7awkzSmEL0YDHmOML0uTGXWuI2k13dPD7O++9TmuELGakJxjXgUFedGcW1NWNDgN2aiurt7kO0ae2XWmCiWnzQiqaiVoYQyKOaFY1P8Mn3GYfQY42qdBF4WRUeqQnB8f2ZHttRTNbI8a3NhhNst+xwvEo1nWGTXMfjhJZ7f30xMm/f133pk1n9bRjLbSG3Rc+zHCQA7s4jVOTbvKTNaZ0RjB8fqyFEAq6gAL9wbrkUjGHdPBEf9v4YEJmvQWQtJzxA/s6I/OePZEH7ezHPDE/z5qwKXy/tKDQZdL4vB8ySgQ5a0VbB8228IBm7BAj36lqqh/0IoajcRjM0sjp0Dge/b6NeTfN2wAjlhqXfzoawEMhv3YgpQMtgRTvt/xSDllpj3g+iAUG07rNxJxxEOsTOselNSdMTBrko8y5QiL2Slz6D2xl10yJTxwlJfHova0VzGwk3qkU6AqATiW5EXnRgA0UZnFO9k+xjiryjeARwTDHcePx6RLN5fxTkHY3y7ZntwbpQhhQzC3NkOL1A4oTORq6N3LGdYFVnG7+GCv8bxmspMGjtNjn58Ix2TIH2lt1TKXmc7wyGjd/0ZO4E6mzktV4DKU/coR4AORr+P1MDCCwYb/TxNPDRhvIyU48YCemoSqHcfouwua0CjCKRx1OpjNgE0ZoVGDYMnzgm5b8TdAj4SSlQNH5AF1Hz387ROGVLHnClHg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my-secret
      namespace: forager-helm
    type: Opaque
