# Template for sealed secrets

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: forager-helm
type: Opaque
data:
  username: dXNlcm5hbWU= # Base64 encoded value of "username"
  password: cGFzc3dvcmQ= # Base64 encoded value of "password"
  mysql_password: dXNlcm5hbWU=
