apiVersion: v2
name: forager-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

# 0.1.4-20230805-020:  remove port config for gear service in deploymeny manifest
# 0.1.4-20230805-021: [unstable] clean up
# 0.1.4-20230805-022:  change gear service from loadbalancer to nodeport
# 0.1.4-20230805-023: fix target service endpoint name gear -> gear-service
# 0.1.4-20230805-024: change static ip name for gear
# 0.1.4-20230805-025: add persistent volume claim
# 0.1.4-20230805-026: add stateful set
# 0.1.4-20230805-026-002
# 0.1.4-20230805-026-003
# 0.1.4-20230805-026-004
# 0.1.4-20230805-027: 0.1.4-20230805-025
# 0.1.4-20230805-029: add placeholder stateful set
# 0.1.4-20230805-030: replace placeholder with actual volume in stateful set
# 0.1.4-20230805-031: statefulset change replica to 2 from 3
# 0.1.4-20230805-032: statefulset change to actual mysql container
# 0.1.4-20230805-033: fix: set MYSQL_ROOT_PASSWORD for mysql set
# 0.1.4-20230805-034: create headless service [mysql-service] for database
# 0.1.4-20230805-035: create loadbalancer service [mysql-service] for database and rename existing [mysql-service] to [mysql-headless-service]
# 0.1.4-20230805-035-002
# 0.1.4-20230805-036 change nodeport for sql to 3306
# 0.1.4-20230805-037 add MYSQL_ROOT_HOST:% to mysql config
# 0.1.4-20230805-038: 0.1.4-20230805-07
# 0.1.4-20230805-039: change sql set rep to 1 and add entrypoint
# 0.1.4-20230805-040: 0.1.4-20230805-039
# 0.1.4-20230805-041: change sql-set scale rep to 2
# 0.1.4-20230805-042: use secret for sql root password
# 0.1.4-20230805-043: change sql set rep to 1, update secret for sql root password

# -----  Replace gear with forager
# NEW LABEL: forager
# [# 0.1.4-20230808-001] Update Ingress
# [# 0.1.4-20230808-002] Update Service
# [0.1.4-20230808-003] Update Deployment
#                       - pull from registry

# ----- connect app to db
# 0.1.4-20230808-004: pull image hash always
# 0.1.4-20230808-005: SPRING_DATASOURCE_URL configmap
# 0.1.4-20230808-006: configmap remove unused var
# 0.1.4-20230808-007: configmap fix namespace
# 0.1.4-20230808-007-006: configmap fix namespace
# 0.1.4-20230808-007-007: set all db env to deployment
# 0.1.4-20230808-007-008: 0.1.4-20230808-007-007
# 0.1.4-20230808-007-009: fix use configmap instead of secret for conn timeout vals
# 0.1.4-20230808-007-010: use database service name

# 0.1.4-20230812-007-001: harden database config
# 0.1.4-20230812-007-002: fix for 001
# 0.1.4-20230812-007-002-002: fix for 001
# 0.1.4-20230812-007-002-003:

version: 0.1.4-20230812-007-002-003

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
# forager-helm     gear-load-balancer                 LoadBalancer   10.223.243.103   34.106.233.143   82:31559/TCP        6h52m
# forager-helm     nginx-load-balancer                LoadBalancer   10.223.254.7     34.106.65.86     81:32145/TCP        6h52m

# noel@yuzhou helm % gcloud compute addresses list
# NAME     ADDRESS/RANGE  TYPE      PURPOSE  NETWORK  REGION    SUBNET  STATUS
# forager  35.217.78.58   EXTERNAL                    us-west3          IN_USE
