apiVersion: v2
name: forager-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.4-20230805-022

# 0.1.4-20230805-020:  remove port config for gear service in deploymeny manifest
# 0.1.4-20230805-021: [unstable] clean up
# 0.1.4-20230805-022:  change gear service from loadbalancer to nodeport

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

# forager-helm     gear-load-balancer                 LoadBalancer   10.223.243.103   34.106.233.143   82:31559/TCP        6h52m
# forager-helm     nginx-load-balancer                LoadBalancer   10.223.254.7     34.106.65.86     81:32145/TCP        6h52m


# noel@yuzhou helm % gcloud compute addresses list               
# NAME     ADDRESS/RANGE  TYPE      PURPOSE  NETWORK  REGION    SUBNET  STATUS
# forager  35.217.78.58   EXTERNAL                    us-west3          IN_USE