apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap-{{ .Release.Name }}
data:
  myvalue: {{ .Release.Name }}
  drink: {{ .Values.favoriteDrink | repeat 2 }}
  unsetkey: {{ .Values.unsetkey | default "unsetval" }}
