apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /usr/share/nginx/html
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: database-pvc
