apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "mysql-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: mysql
        volumeMounts:
        - name: mysql-vol-placeholder
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol-placeholder
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi