apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-stateful-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: forager-mysql
        image: mysql/mysql-server:8.0.28
        ports:
        - containerPort: 80
          name: mysql-port
        volumeMounts:
        - name: database-pvc-vol
          mountPath: /var/lib/sql
      volumes:
      - name: database-pvc-vol
        persistentVolumeClaim:
          claimName: database-pvc


