apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
  namespace: forager-helm
data:
  spring_datasource_url: jdbc:mysql://{{ .Values.databaseHeadlessServiceName }}:{{ .Values.databaseSvcPort }}/app?createDatabaseIfNotExist=true
  spring_datasource_username: root
  spring_jpa_properties_hibernate_dialect: org.hibernate.dialect.MySQLDialect
  spring_datasource_hikari_connectiontimeout: "3000"
  spring_datasource_hikari_initializationfailtimeout: "-1"