apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-pod
spec:
  volumes:
    - name: pvc-vol
      persistentVolumeClaim:
       claimName: database-pvc
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: pvc-demo-vol