apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - port: 3308
      targetPort: 3306