apiVersion: apps/v1
kind: Deployment
metadata:
  name: forager-fe
  labels:
    app: forager-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forager-fe
  template:
    metadata:
      labels:
        app: forager-fe
    spec:
      containers:
        - name: forager-fe
          image: noellimdev1/forager-fe:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80

