apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeportServiceForagerFE }}
spec:
  selector:
    app: forager-fe
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort

