apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingressServiceForager }}
spec:
  selector:
    app: forager
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

