apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my-secret
  namespace: forager-helm
spec:
  encryptedData:
    mysql_password: AgBvVIXpQ9iFM/Bz5YFTQ+8qUJK7fhj9/KNisQxeIqVitWNjyCs9V4sdjoEfHgEfRCmi+c2M7OlTPUYWgouDwZNty8c40NyAfTYzUhaxZxg7FVmw5vFS/T10AwV4tmc3TWCPY/QamH07Tjp3JGa6IDcZnkGNgQwk77B8QaJ5W221BPe1fh99TnF+lt+uJuBT4Q9g7+4mZePMj2nixwKJVhkfwDhkwjCE5lcd7pZiLhaARkbRIbeutXXOkv9iqDHg8YDfQvLmNikVcHr+L1hnhn6Qy2aYMPSbu7uqCcCXKIOhaemc8Ubd0uG1M0rEFUjvGbpQauBD3piPhK+0qSWMnmq5VN86hCTf4MTM+fFex294de9jucQgkFyhXLtVOrbBw1NTayCvBNbjNom5sfjAQp96AwEdvaMZ0qfrvb+FINVW+mexVWcAN6x4a5Sg0vevKnpZxnpqJD2yB/Yd88rQz+mBS0+/jOYguCg3CsExpP9PL+/4jRmqY7wMpzVTZtRTIOrdf0xPiDjjq4BqKa2YlVzpQeOyyC/2iyJ3PvzWUkExT1Had3lMCuBPdv+Ro93gXZQrguMycpZBE2RovrcMGIbv4Ovu3W7duzmd5k85MSexIB872orAUO78PswtShsrTYyMwEj+mCw6HvlTbn4WFVfWnUBlH+9bJN/t+Kc/oqP0QLgSc9VadXtRHlT64VHavya2AjrV5wulfg==
    password: AgArG4oN3vNC0vXHmjTN57QtBgYdBLf83S5Yn1+Ch0FpdMc0eO8rMMow07I5gJ7tQ43k9Ru0pVU1ncUi4Ey1ZyglIsALpMv4QGs0bpgG0wa5asIRvJqIMQf1kgPvSNmx22sn1i76uFw9I6uwYo9M5UX7iXQzCOqdA5+pj42pQ5Rh6NbFH0wUEdhe6w5zQjo3c7JZbjpwaSSNd7a+kk//eETBCpLZvJV6dZsaap/NCdnHFdoz2HNLTmu7MGUbU/hWPzgno4TEZC5HIf0n6aCFRp6qiRgbAwtrU+Y0Ex5m7BOaayF1QKNY3rHZr3an3nOwGAQ3/djcBqs6XdsDeNZXFqwwG9vgAGWujFIlosIWL37LYTOIr7A19xKCh5fpPZLgfKAprEON0rT/nTfq0+uvT+m3y/5GimHlf/0uXYTAQIQ/E5pAta6sZuwD8bOp7C/H8lDc67Fd9v/1AMDMZyhzikMLLP2KT8Ju3vc9G64P+yl5uQix4rd13p3mqs8geKvBO0+uhW3dQ7XfQHEa/C02lKQF1uLcsQcLs3anycS+EhLbqx5eBSHl/e5IHHmraoGgPZzzyRbm7eFOaebKyPndNhf5nufJrmgy5wnrpIS0iXm8WWmjZES5u8bH2QjUGRElCYmhh6y911aPCnpjCr4TK6psOkY9A2E5MvseR5yBse7940w4jWdZy9mbRF4taD2nkDL48D0CsU4n3A==
    username: AgCdE4d2F010m3Sdx7HGJQdB1wbCR69rjfJ+GKCmUh4jXps+yJPLViDVRWAoBrIxCKfrORQtZ/6N1+mKelLMl4wgtlKBZBupy9NnxNIf7Z4GClI7OERnN3rc1CoE8R1adlzmsrSij4QfgF5UFdZahFNajIVfF38fOHppRjtwdIZo7iE9oOl/8lTJLcFpeoojmu11jratPddu3XTteEDq97FKiLcycEOmZL0Qr+YsJhvi7ycdalqKhIS6e02tNTE580OM+LJ+KMFIeQHu6iKMxpCgr+h/a0aaU4HyMeL2Xxla94QkCEf0N3aX++cEUmmCHabhbP+tAE4POiM+iBf7D2FiKnPRgb0Y452/QK/TpcVHXvvsCOiHctta6BNI4ByjQ+TsMPdGW3n7iyjTOc75HZqCPjAMF2E2NygS2rRJbgbOf3zm0HKGRo47g4n+X7A70kt5EFCPXoongbHcjdHx09TVmuRcduQbeFv4ImNg/JqfYHEMMtXCf/rrYqAeAQGgOGOl4M064MBM7PJ6jqBm/MCeF350zfRWmJQ6lDxmDVW/nsgS7RcfMnzdjCvqtsNWSi7EyZ8Vorivfb/HYroZ9MhpGO5eu8hUvblbSP30JSyVx45wlFD0DR9X+F0gKHNiN5RpXZUOmLxA/B3ihtnGnZbh0CPixiXm05/ior7uVjLF+tq7k/4MB2fDzVUCQPbT9vbXPnueUyAjUg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my-secret
      namespace: forager-helm
    type: Opaque

