apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    # nginx.conf

    events {}

    http {
        server {
            location /hello {
                # Using the `echo` module to return the value of the environment variable
                return 302 /$my_variable;
            }
        }
    }
