apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginxVersion | default "nginx:1.16.0" }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 81
              protocol: TCP


